export const SETTING_MENU_FAILURE: string = "SETTING_MENU_FAILURE";
export const SETTING_MENU_LOAD_DATA: string = "SETTING_MENU_LOAD_DATA";
export const SETTING_MENU_LOAD_DATA_SUCCESS: string =
  "SETTING_MENU_LOAD_DATA_SUCCESS";
export const SETTING_MENU_HYDRATE: string = "SETTING_MENU_HYDRATE";
